version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: lazyglab
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: lazyglab
    package_name: lazyglab
    vendor: Malvi1697
    homepage: https://github.com/Malvi1697/lazyglab
    maintainer: Jan Vseticek
    description: Terminal UI for GitLab, inspired by lazygit
    license: MIT
    formats:
      - deb
      - rpm

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^ci:"
      - "^test:"

release:
  github:
    owner: Malvi1697
    name: lazyglab
  draft: false
  prerelease: auto
